require:
  - rubocop-performance

AllCops:
  SuggestExtensions: false

Metrics/ClassLength:
  Exclude:
    - 'lib/what_dya_return/extractor.rb'
    - 'lib/what_dya_return/processor.rb'
    - 'test/what_dya_return/extractor_test.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'test/*'

Style/Documentation:
  Enabled: false
